use_frameworks!

platform :ios, '10.0'

target 'HMComponent_Example' do
  pod 'HMComponent', :git => 'git@github.com:pelsor/HMComponent.git'

  target 'HMComponent_Tests' do
    inherit! :search_paths

    
  end
end
